/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as DateImport } from "./routes/$date"

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")()

// Create/Update Routes

const DateRoute = DateImport.update({
    path: "/$date",
    getParentRoute: () => rootRoute
} as any)

const IndexLazyRoute = IndexLazyImport.update({
    path: "/",
    getParentRoute: () => rootRoute
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/"
            path: "/"
            fullPath: "/"
            preLoaderRoute: typeof IndexLazyImport
            parentRoute: typeof rootRoute
        }
        "/$date": {
            id: "/$date"
            path: "/$date"
            fullPath: "/$date"
            preLoaderRoute: typeof DateImport
            parentRoute: typeof rootRoute
        }
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexLazyRoute, DateRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$date"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$date": {
      "filePath": "$date.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
